### ISSUE TITLE
Work with dwg in android

### ISSUE THREAD

**Issue by Sergey63** [Developer-Autodesk/workflow-android-view.and.data.api#1]
Hi.
I want create android application with next features - create, view and edit dwg file for get experience work with android and dwg files. But i noticed that this example use browser. Could you give me advice?

**Comment by leefsmp** [comment]
Hi Sergey, unfortunately at the moment there is no API provided by Autodesk that allows you to create, view or edit .dwg on mobile platforms. You can use the AutoCAD.IO web service which can be invoked by http calls from an android app. This allows you to create, query and edit .dwg. You can then use View & Data API to view the .dwg inside a webview.

Here are links to the developer documentation, let us know if you have more specific questions:

https://developer.autodesk.com/api/autocadio
https://developer.autodesk.com/api/view-and-data-api

**Comment by IdioticMadman** [comment]
@Sergey63 Have you solve problem? Can give some advise to me?

**Comment by leefsmp** [comment]
I don't think anybody can "solve" the problem with couple lines of code, as I mentioned in my previous reply no available technology at the moment allows to perform direct edits of a .dwg on a mobile device. Take a look at the links I provided.

**Comment by Sanmoy1** [comment]
Is there any api to work with .dwg file now?
